# Generated by Django 4.1.7 on 2023-08-25 02:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Academia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=9)),
                ('web', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('academia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.academia')),
            ],
        ),
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Profesor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido_paterno', models.CharField(max_length=100)),
                ('apellido_materno', models.CharField(max_length=100)),
                ('email', models.CharField(max_length=50)),
                ('telefono', models.CharField(max_length=9)),
                ('academia_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.academia')),
            ],
        ),
        migrations.CreateModel(
            name='Nota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.alumno')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.curso')),
            ],
        ),
        migrations.AddField(
            model_name='curso',
            name='profesor_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.profesor'),
        ),
        migrations.CreateModel(
            name='Alumno_x_Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alumno_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.alumno')),
                ('curso_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facultades.curso')),
            ],
        ),
    ]
